// Used in development
const tempResponse = {
  complete_matches: [
    {
      enroll_date: "11-18-2018",
      exit_date: "01-13-2019",
      exit_destination: "Rental by client, other ongoing housing subsidy",
      first_name: "paul",
      income_at_entry: null,
      income_at_exit: 569.0,
      last_name: "smith",
    },
    {
      enroll_date: "06-14-2018",
      exit_date: "07-28-2018",
      exit_destination:
        "Emergency shelter, including hotel or motel paid for with emergency shelter voucher, or RHY-funded Host Home shelter",
      first_name: "paul",
      income_at_entry: null,
      income_at_exit: 459.0,
      last_name: "smith",
    },
    {
      enroll_date: "10-25-2018",
      exit_date: "11-18-2018",
      exit_destination:
        "Emergency shelter, including hotel or motel paid for with emergency shelter voucher, or RHY-funded Host Home shelter",
      first_name: "paul",
      income_at_entry: 569.0,
      income_at_exit: 569.0,
      last_name: "smith",
    },
    {
      enroll_date: "12-01-2018",
      exit_date: null,
      exit_destination: null,
      first_name: "paul",
      income_at_entry: null,
      income_at_exit: null,
      last_name: "smith",
    },
    {
      enroll_date: "11-18-2018",
      exit_date: "01-13-2019",
      exit_destination: "Rental by client, other ongoing housing subsidy",
      first_name: "paul",
      income_at_entry: null,
      income_at_exit: 569.0,
      last_name: "smith",
    },
    {
      enroll_date: "06-14-2018",
      exit_date: "07-28-2018",
      exit_destination:
        "Emergency shelter, including hotel or motel paid for with emergency shelter voucher, or RHY-funded Host Home shelter",
      first_name: "paul",
      income_at_entry: null,
      income_at_exit: 459.0,
      last_name: "smith",
    },
    {
      enroll_date: "10-25-2018",
      exit_date: "11-18-2018",
      exit_destination:
        "Emergency shelter, including hotel or motel paid for with emergency shelter voucher, or RHY-funded Host Home shelter",
      first_name: "paul",
      income_at_entry: 569.0,
      income_at_exit: 569.0,
      last_name: "smith",
    },
    {
      enroll_date: "12-01-2018",
      exit_date: null,
      exit_destination: null,
      first_name: "paul",
      income_at_entry: null,
      income_at_exit: null,
      last_name: "smith",
    },
  ],
  partial_matches: [
    {
      enroll_date: "11-18-2018",
      exit_date: "01-13-2019",
      exit_destination: "Rental by client, other ongoing housing subsidy",
      first_name: "paul",
      income_at_entry: null,
      income_at_exit: 569.0,
      last_name: "smith",
    },
    {
      enroll_date: "11-18-2018",
      exit_date: "01-13-2019",
      exit_destination: "Rental by client, other ongoing housing subsidy",
      first_name: "paul",
      income_at_entry: null,
      income_at_exit: 569.0,
      last_name: "smith",
    },
    {
      enroll_date: "11-18-2018",
      exit_date: "01-13-2019",
      exit_destination: "Rental by client, other ongoing housing subsidy",
      first_name: "paul",
      income_at_entry: null,
      income_at_exit: 569.0,
      last_name: "smith",
    },
    {
      enroll_date: "11-18-2018",
      exit_date: "01-13-2019",
      exit_destination: "Rental by client, other ongoing housing subsidy",
      first_name: "paul",
      income_at_entry: null,
      income_at_exit: 569.0,
      last_name: "smith",
    },
    {
      enroll_date: "11-18-2018",
      exit_date: "01-13-2019",
      exit_destination: "Rental by client, other ongoing housing subsidy",
      first_name: "paul",
      income_at_entry: null,
      income_at_exit: 569.0,
      last_name: "smith",
    },
    {
      enroll_date: "11-18-2018",
      exit_date: "01-13-2019",
      exit_destination: "Rental by client, other ongoing housing subsidy",
      first_name: "paul",
      income_at_entry: null,
      income_at_exit: 569.0,
      last_name: "smith",
    },
  ],
};

export default tempResponse;
